### ISSUE TITLE
problem with startup

### ISSUE THREAD

**Issue by BlackGlassSkin** [micky4966/iptvunion#1]
Hi.
what it requires to work properly
i have nice iptv installed and it works fine
iptvunion can't start ...

thanks.

**Comment by micky4966** [comment]
> 
> 
> Hi.
> what it requires to work properly
> i have nice iptv installed and it works fine
> iptvunion can't start ...
> 
> thanks.

Hello,
it was a bin file permissions issue, now it's OK
Regards
